#remote_theme: pages-themes/midnight@v0.2.0
#plugins:
#- jekyll-remote-theme
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
search_enabled: true
version: false
sidebar:
  - 01-introduccion
  - 02-variables
  - 03-estructuras
  - 04-funciones
  - 05-types
  - 06-cli
  - 07-archivos
  - 08-ejercicios
  - separador-01
  - 09-json
  - 10-interfaces